version: "3.9"
services:
  postgres:
    container_name: postgres_blog
    image: "postgres:13.2"
    env_file:
      - ./database.env
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - ":5432"
  pgadmin:
    container_name: pgadmin_blog
    image: "dpage/pgadmin4:5.1"
    env_file:
      - ./database.env
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - backend
  keycloak:
    container_name: CyberExamContainer
    image: "emilianonigro/cybersecexam:latest"
    depends_on:
      - "postgres"
    env_file:
      - ./keycloak.env
    ports:
      - "8080:8080"
    command: 
      - start-dev 
      - --import-realm 
    volumes:
      - ./imports:/opt/keycloak/data
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge